[module]

  [module.hugoVersion]
    # This version of Wowchemy is compatible with the following Hugo versions:
    min = "0.73.0"
    extended = true

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"
